# Generated by Django 5.0.7 on 2024-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_email_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
