# Generated by Django 5.0.7 on 2024-08-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learned_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
