# Generated by Django 5.0.7 on 2024-08-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_learned_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='learned_count',
            new_name='saved_count',
        ),
    ]
