# Generated by Django 5.0.7 on 2024-07-20 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_algorithm', message='Invalid alogrithm.', regex="^([RLUDFBMESxyz]{1}[']? *)+$")]),
        ),
    ]
