# Generated by Django 5.0.7 on 2024-07-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_alter_algorithm_content'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
