# Generated by Django 5.0.7 on 2024-07-29 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_alter_algorithm_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_algorithm', message='Invalid alogrithm.', regex="^([RLUDFBMESrludfbxyz]{1}['2]? *)+$")]),
        ),
    ]
