# Generated by Django 5.0.7 on 2024-07-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_alter_algorithm_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, default='/algorithms/default.png', null=True, upload_to='algorithms/'),
        ),
    ]
