# Generated by Django 5.0.7 on 2024-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0009_algorithm_cube_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='cube_state',
            field=models.CharField(default='wwwwwwwwwyyyyyyyyyrrrrrrrrrooooooooogggggggggbbbbbbbbb', max_length=54),
        ),
    ]
