# Generated by Django 5.0.7 on 2024-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0011_alter_algorithm_cube_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, default='/algorithms/default.png', editable=False, null=True, upload_to='algorithms/'),
        ),
    ]
