# Generated by Django 5.0.7 on 2024-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0012_alter_algorithm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='hearts_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
