# Generated by Django 5.0.7 on 2024-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0013_algorithm_hearts_count'),
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='hearts_count',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='users_hearts',
            field=models.ManyToManyField(blank=True, related_name='hearts', to='profiles.profile'),
        ),
    ]
