# Generated by Django 5.0.7 on 2024-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0014_remove_algorithm_hearts_count_algorithm_users_hearts'),
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='users_hearts',
            field=models.ManyToManyField(blank=True, related_name='hearted_users', to='profiles.profile'),
        ),
    ]
