# Generated by Django 5.0.7 on 2024-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0016_alter_algorithm_users_hearts'),
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='users_learned',
            field=models.ManyToManyField(blank=True, related_name='learned_algs', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='users_hearts',
            field=models.ManyToManyField(blank=True, related_name='hearted_algs', to='profiles.profile'),
        ),
    ]
