# Generated by Django 5.0.7 on 2024-08-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0017_algorithm_users_learned_alter_algorithm_users_hearts'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='heart_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='learned_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
