# Generated by Django 5.0.7 on 2024-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0018_algorithm_heart_count_algorithm_learned_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='algorithms/'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='algs', to='algorithms.tag'),
        ),
    ]
