# Generated by Django 5.0.7 on 2024-08-31 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0020_rename_learned_count_algorithm_saved_count_and_more'),
        ('profiles', '0005_rename_learned_count_profile_saved_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_algorithm', message='Invalid alogrithm.', regex="^( |\\n|\\/\\/[^\\n]*)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|\\/\\/[^\\n]*)+)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|\\/\\/[^\\n]*)*){1}$")]),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='users_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_algs', to='profiles.profile'),
        ),
    ]
