# Generated by Django 5.0.7 on 2024-08-31 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0021_alter_algorithm_content_alter_algorithm_users_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_algorithm', message='Invalid alogrithm.', regex="^( |\\n|\\/\\/[^\\n]*)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|\\/\\/[^\\n]*)+)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|\\/\\/[^\\n]*)*){1}$")]),
        ),
    ]
