# Generated by Django 5.0.7 on 2024-09-07 14:51

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0022_alter_algorithm_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(code='invalid_algorithm', flags=re.RegexFlag['MULTILINE'], message='Invalid alogrithm.', regex="^( |\\n|//[^\\n]*)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|//[^\\n]*)+)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|//[^\\n]*)*){1}$")]),
        ),
    ]
