# Generated by Django 5.0.7 on 2024-09-10 15:08

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0023_alter_algorithm_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='scramble',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_scramble', message='Invalid scramble.', regex="^([RLUDFBMESrludfbxyz]{1}([2]|[']|2')? +)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')? *){1}$")]),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='content',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(code='invalid_solve', flags=re.RegexFlag['MULTILINE'], message='Invalid solve.', regex="^( |\\n|//[^\\n]*)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|//[^\\n]*)+)*([RLUDFBMESrludfbxyz]{1}([2]|[']|2')?( |\\n|//[^\\n]*)*){1}$")]),
        ),
    ]
