# Generated by Django 5.0.7 on 2024-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0024_algorithm_scramble_alter_algorithm_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
