# Generated by Django 5.0.7 on 2024-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0025_alter_algorithm_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='name',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='solver',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
