# Generated by Django 5.0.7 on 2024-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0026_remove_algorithm_name_algorithm_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
