# Generated by Django 5.0.7 on 2024-09-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0028_alter_algorithm_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['-heart_count', '-date_added']},
        ),
    ]
